import Head from "next/head";
import Header from "./Header";
import Footer from "./Footer";
import { ChakraProvider } from "@chakra-ui/react";

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Somnium Space</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ChakraProvider>
        <Header />
        <main role="main">{children}</main>
        <Footer />
      </ChakraProvider>
    </>
  );
};
export default Layout;
